export interface Airport {
    code: string;
    name: string;
    city: string;
    country: string;
}

export const AIRPORTS: Airport[] = [
    // Algérie
    { code: 'ALG', name: 'Aéroport d\'Alger-Houari Boumédiène', city: 'Alger', country: 'Algérie' },
    { code: 'ORN', name: 'Aéroport d\'Oran - Ahmed Ben Bella', city: 'Oran', country: 'Algérie' },
    { code: 'CZL', name: 'Aéroport de Constantine - Mohamed Boudiaf', city: 'Constantine', country: 'Algérie' },
    { code: 'AAE', name: 'Aéroport d\'Annaba - Rabah Bitat', city: 'Annaba', country: 'Algérie' },
    { code: 'BJA', name: 'Aéroport de Béjaïa - Soummam Abane Ramdane', city: 'Béjaïa', country: 'Algérie' },
    { code: 'TLM', name: 'Aéroport de Tlemcen - Zenata-Messali El Hadj', city: 'Tlemcen', country: 'Algérie' },

    // France
    { code: 'CDG', name: 'Aéroport de Paris-Charles de Gaulle', city: 'Paris', country: 'France' },
    { code: 'ORY', name: 'Aéroport de Paris-Orly', city: 'Paris', country: 'France' },
    { code: 'LYS', name: 'Aéroport de Lyon-Saint-Exupéry', city: 'Lyon', country: 'France' },
    { code: 'MRS', name: 'Aéroport de Marseille-Provence', city: 'Marseille', country: 'France' },
    { code: 'NCE', name: 'Aéroport de Nice-Côte d\'Azur', city: 'Nice', country: 'France' },
    { code: 'TLS', name: 'Aéroport de Toulouse-Blagnac', city: 'Toulouse', country: 'France' },

    // International
    { code: 'TUN', name: 'Aéroport de Tunis-Carthage', city: 'Tunis', country: 'Tunisie' },
    { code: 'DJE', name: 'Aéroport de Djerba-Zarzis', city: 'Djerba', country: 'Tunisie' },
    { code: 'CMN', name: 'Aéroport Mohammed V de Casablanca', city: 'Casablanca', country: 'Maroc' },
    { code: 'RAK', name: 'Aéroport de Marrakech-Ménara', city: 'Marrakech', country: 'Maroc' },
    { code: 'IST', name: 'Aéroport d\'Istanbul', city: 'Istanbul', country: 'Turquie' },
    { code: 'SAW', name: 'Aéroport international Sabiha Gökçen', city: 'Istanbul', country: 'Turquie' },
    { code: 'DXB', name: 'Aéroport international de Dubaï', city: 'Dubaï', country: 'Émirats Arabes Unis' },
    { code: 'JED', name: 'Aéroport international Roi-Abdelaziz', city: 'Djeddah', country: 'Arabie Saoudite' },
    { code: 'MED', name: 'Aéroport international Prince Mohammad Bin Abdulaziz', city: 'Médine', country: 'Arabie Saoudite' },
    { code: 'RUH', name: 'Aéroport international du roi Khaled', city: 'Riyad', country: 'Arabie Saoudite' },
    { code: 'DOH', name: 'Aéroport international de Hamad', city: 'Doha', country: 'Qatar' },
    { code: 'LHR', name: 'Aéroport de Londres-Heathrow', city: 'Londres', country: 'Royaume-Uni' },
    { code: 'MAD', name: 'Aéroport Adolfo-Suárez de Madrid-Barajas', city: 'Madrid', country: 'Espagne' },
    { code: 'BCN', name: 'Aéroport de Barcelone-El Prat', city: 'Barcelone', country: 'Espagne' },
    { code: 'FCO', name: 'Aéroport de Rome-Fiumicino', city: 'Rome', country: 'Italie' },
    { code: 'MXP', name: 'Aéroport de Milan-Malpensa', city: 'Milan', country: 'Italie' },
    { code: 'FRA', name: 'Aéroport de Francfort-sur-le-Main', city: 'Francfort', country: 'Allemagne' },
    { code: 'BRU', name: 'Aéroport de Bruxelles-National', city: 'Bruxelles', country: 'Belgique' },
    { code: 'GVA', name: 'Aéroport international de Genève', city: 'Genève', country: 'Suisse' },
    { code: 'YUL', name: 'Aéroport international Pierre-Elliott-Trudeau de Montréal', city: 'Montréal', country: 'Canada' },
    { code: 'JFK', name: 'Aéroport international de New York-John F. Kennedy', city: 'New York', country: 'États-Unis' },
    { code: 'IAD', name: 'Aéroport international de Washington-Dulles', city: 'Washington', country: 'États-Unis' },
    { code: 'BKK', name: 'Aéroport de Bangkok-Suvarnabhumi', city: 'Bangkok', country: 'Thaïlande' },
    { code: 'CAN', name: 'Aéroport international de Canton-Baiyun', city: 'Canton', country: 'Chine' },
    { code: 'KUL', name: 'Aéroport international de Kuala Lumpur', city: 'Kuala Lumpur', country: 'Malaisie' },
    { code: 'CAI', name: 'Aéroport international du Caire', city: 'Le Caire', country: 'Égypte' },
    { code: 'BEY', name: 'Aéroport international de Beyrouth', city: 'Beyrouth', country: 'Liban' },
    { code: 'AMM', name: 'Aéroport international Reine-Alia', city: 'Amman', country: 'Jordanie' },
    { code: 'LCY', name: 'Aéroport de Londres-City', city: 'Londres', country: 'Royaume-Uni' },
    { code: 'CDG', name: 'Aéroport de Paris-Charles de Gaulle', city: 'Paris', country: 'France' },
    { code: 'AMS', name: 'Aéroport d\'Amsterdam-Schiphol', city: 'Amsterdam', country: 'Pays-Bas' },
    { code: 'ZRH', name: 'Aéroport international de Zurich', city: 'Zurich', country: 'Suisse' },
    { code: 'VIE', name: 'Aéroport de Vienne-Schwechat', city: 'Vienne', country: 'Autriche' },
    { code: 'LIS', name: 'Aéroport de Lisbonne-Humberto Delgado', city: 'Lisbonne', country: 'Portugal' },
    { code: 'ATH', name: 'Aéroport international d\'Athènes Elefthérios-Venizélos', city: 'Athènes', country: 'Grèce' },
    { code: 'DUB', name: 'Aéroport de Dublin', city: 'Dublin', country: 'Irlande' },
    { code: 'STH', name: 'Aéroport de Stockholm-Arlanda', city: 'Stockholm', country: 'Suède' },
    { code: 'OSL', name: 'Aéroport d\'Oslo-Gardermoen', city: 'Oslo', country: 'Norvège' },
    { code: 'CPH', name: 'Aéroport de Copenhague', city: 'Copenhague', country: 'Danemark' },
    { code: 'DEL', name: 'Aéroport international Indira-Gandhi', city: 'Delhi', country: 'Inde' },
    { code: 'BOM', name: 'Aéroport international Chhatrapati-Shivaji', city: 'Bombay', country: 'Inde' },
    { code: 'NRT', name: 'Aéroport international de Narita', city: 'Tokyo', country: 'Japon' },
    { code: 'HND', name: 'Aéroport international de Tokyo-Haneda', city: 'Tokyo', country: 'Japon' },
    { code: 'ICN', name: 'Aéroport international d\'Incheon', city: 'Séoul', country: 'Corée du Sud' },
    { code: 'SIN', name: 'Aéroport de Singapour-Changi', city: 'Singapour', country: 'Singapour' },
    { code: 'SYD', name: 'Aéroport de Sydney', city: 'Sydney', country: 'Australie' },
    { code: 'MEL', name: 'Aéroport de Melbourne', city: 'Melbourne', country: 'Australie' },
    { code: 'GRU', name: 'Aéroport international de Guarulhos', city: 'São Paulo', country: 'Brésil' },
    { code: 'MEX', name: 'Aéroport international de Mexico', city: 'Mexico', country: 'Mexique' },
    { code: 'EZE', name: 'Aéroport international d\'Ezeiza', city: 'Buenos Aires', country: 'Argentine' },
    { code: 'CPT', name: 'Aéroport international du Cap', city: 'Le Cap', country: 'Afrique du Sud' },
    { code: 'JNB', name: 'Aéroport international OR Tambo', city: 'Johannesbourg', country: 'Afrique du Sud' },
    { code: 'NBO', name: 'Aéroport international Jomo-Kenyatta', city: 'Nairobi', country: 'Kenya' },
    { code: 'DSS', name: 'Aéroport international Blaise-Diagne', city: 'Dakar', country: 'Sénégal' },
    { code: 'CMN', name: 'Aéroport Mohammed V de Casablanca', city: 'Casablanca', country: 'Maroc' },
    { code: 'RUH', name: 'Aéroport international du roi Khaled', city: 'Riyad', country: 'Arabie Saoudite' },
    { code: 'MED', name: 'Aéroport international Prince Mohammad Bin Abdulaziz', city: 'Médine', country: 'Arabie Saoudite' },
    { code: 'KRT', name: 'Aéroport international de Khartoum', city: 'Khartoum', country: 'Soudan' },
    { code: 'TUN', name: 'Aéroport de Tunis-Carthage', city: 'Tunis', country: 'Tunisie' },
    { code: 'RAK', name: 'Aéroport de Marrakech-Ménara', city: 'Marrakech', country: 'Maroc' },
    { code: 'BLQ', name: 'Aéroport de Bologne-Borgo Panigale', city: 'Bologne', country: 'Italie' },
    { code: 'VCE', name: 'Aéroport de Venise-Marco Polo', city: 'Venise', country: 'Italie' },
    { code: 'PRG', name: 'Aéroport de Prague-Václav-Havel', city: 'Prague', country: 'République Tchèque' },
    { code: 'WAW', name: 'Aéroport Chopin de Varsovie', city: 'Varsovie', country: 'Pologne' },
    { code: 'BUD', name: 'Aéroport international de Budapest-Ferenc Liszt', city: 'Budapest', country: 'Hongrie' },
    { code: 'SVO', name: 'Aéroport international Cheremetievo', city: 'Moscou', country: 'Russie' },
    { code: 'ATH', name: 'Aéroport international d\'Athènes', city: 'Athènes', country: 'Grèce' },
    { code: 'RUH', name: 'Aéroport international du roi Khaled', city: 'Riyad', country: 'Arabie Saoudite' },
    { code: 'DMM', name: 'Aéroport international du roi Fahd', city: 'Dammam', country: 'Arabie Saoudite' },
    { code: 'KWI', name: 'Aéroport international de Koweït', city: 'Koweït', country: 'Koweït' },
    { code: 'MCT', name: 'Aéroport international de Mascate', city: 'Mascate', country: 'Oman' },
    { code: 'BAH', name: 'Aéroport international de Bahreïn', city: 'Manama', country: 'Bahreïn' },
    { code: 'IKA', name: 'Aéroport international Imam Khomeini', city: 'Téhéran', country: 'Iran' },
    { code: 'KHI', name: 'Aéroport international Jinnah', city: 'Karachi', country: 'Pakistan' },
    { code: 'LHE', name: 'Aéroport international Allama Iqbal', city: 'Lahore', country: 'Pakistan' },
    { code: 'DAC', name: 'Aéroport international Shah Jalal', city: 'Dacca', country: 'Bangladesh' },
    { code: 'CMB', name: 'Aéroport international Bandaranaike', city: 'Colombo', country: 'Sri Lanka' },
    { code: 'MLE', name: 'Aéroport international de Malé', city: 'Malé', country: 'Maldives' },
    { code: 'SGN', name: 'Aéroport international de Tan Son Nhat', city: 'Ho Chi Minh Ville', country: 'Vietnam' },
    { code: 'HAN', name: 'Aéroport international de Noi Bai', city: 'Hanoï', country: 'Vietnam' },
    { code: 'MNL', name: 'Aéroport international Ninoy Aquino', city: 'Manille', country: 'Philippines' },
    { code: 'CGK', name: 'Aéroport international Soekarno-Hatta', city: 'Jakarta', country: 'Indonésie' },
    { code: 'DPS', name: 'Aéroport international Ngurah Rai', city: 'Bali', country: 'Indonésie' },
    { code: 'LAX', name: 'Aéroport international de Los Angeles', city: 'Los Angeles', country: 'États-Unis' },
    { code: 'SFO', name: 'Aéroport international de San Francisco', city: 'San Francisco', country: 'États-Unis' },
    { code: 'ORD', name: 'Aéroport international O\'Hare de Chicago', city: 'Chicago', country: 'États-Unis' },
    { code: 'MIA', name: 'Aéroport international de Miami', city: 'Miami', country: 'États-Unis' },
    { code: 'YYZ', name: 'Aéroport international Pearson de Toronto', city: 'Toronto', country: 'Canada' },
    { code: 'YVR', name: 'Aéroport international de Vancouver', city: 'Vancouver', country: 'Canada' }
];
